const { defineConfig } = require("@vue/cli-service");
module.exports = defineConfig({
  css: {
    loaderOptions: {
      sass: {
        additionalData: `
        @import "@/styles/variables.scss";
        @import "@/styles/animations.scss";
        @import "@/styles/layout.scss";
        @import "@/styles/typography.scss";
        @import "@/styles/main.scss";
        `
      }
    }
  },
  transpileDependencies: true,
  // publicPath: process.env.NODE_ENV === "production" ? "./" : "./",
  publicPath: "",
  assetsDir: process.env.NODE_ENV === "production" ? "common" : "",
  // By default, generated static assets contains hashes in their filenames for better caching control.
  // However, this requires the index HTML to be auto-generated by Vue CLI. If you cannot make use of the index HTML
  // generated by Vue CLI, you can disable filename hashing by setting this option to false,
  filenameHashing: false,
  lintOnSave: false,
  chainWebpack: config => {
    config.plugin("html").tap(args => {
      args[0].minify = false;
      // args[0].template = "public/session/1/ELFH_Session/1/index.html"; // you can specify the location of index.html if necessary
      // args[0].template = "./index.html.template";
      return args;
    });
  },
  configureWebpack: config => {
    config.devtool = "source-map";
    config.optimization.minimize = false;
  }
});
